CREATE TABLE IF NOT EXISTS popular_articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(512) NOT NULL,
  source_url VARCHAR(2048) NOT NULL,
  clicks_count INT NOT NULL DEFAULT 0,
  last_clicked_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_article_url (source_url(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS popular_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(512) NOT NULL,
  company_name VARCHAR(255) DEFAULT NULL,
  source_url VARCHAR(2048) DEFAULT NULL,
  clicks_count INT NOT NULL DEFAULT 0,
  last_clicked_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_job_url (source_url(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

